### ISSUE TITLE
Signalstore versioning

### ISSUE THREAD

**Issue by arnodelorme** [olivershetler/SignalStore#2]
We might have several versions of 2 datasets.
- If this is the case, create an additional entry in Signalstore
- Add the version (v2), maybe all the datasets are v1 by default
- Update the field "lastest" which is 0 or 1 (set the old dataset to 0 and the new dataset to 1). This field can be used as a filter during search (the search takes the latest dataset by default).

**Comment by olivershetler** [comment]
Hi @arnodelorme we already support versions for individual data objects. I apologize that the feature isn't fully documented in this alpha pre-release. Please have a look at the unit tests for the data repository to see how versioned data are expected to behave.

**Comment by arnodelorme** [comment]
Apologies. We have a fork, and these issues were meant for it.

**Comment by arnodelorme** [comment]
@dungscout96 version for datasets is supported.
