### ISSUE TITLE
MongodB and S3 consistency

### ISSUE THREAD

**Issue by arnodelorme** [olivershetler/SignalStore#3]
Build a script that 
1- ensures consistency between MongodB and S3. The script downloads locally all the data form S3, making sure it is not corrupted.
2- potentially recreate mongoDb from S3 data

**Comment by olivershetler** [comment]
@arnodelorme you can verify the consistency by running a query for all the data with the has_file flag marked as True, and then you can call exists method on each key (schema_ref, data_name) to verify that the file exists as expected in the S3 bucket.

**Comment by arnodelorme** [comment]
Apologies. We have a fork, and these issues were meant for it.
