### ISSUE TITLE
MongodB security

### ISSUE THREAD

**Issue by arnodelorme** [olivershetler/SignalStore#4]
Add security to MongoDb on EC2

**Comment by olivershetler** [comment]
@arnodelorme We currently let the user define the MongoDB client using PyMongo, meaning that you should be able to implement security protocols prior to injecting that dependency into the UnitOfWorkProvider. 

However, we may not have anticipated all scenarios. If you have a specific suggestions, please feel free to reach out to me on LinkedIn and we can set up a call. https://www.linkedin.com/in/olivershetler

**Comment by arnodelorme** [comment]
Apologies. We have a fork, and these issues were meant for it.
